import { __ } from '@wordpress/i18n';

export default [
    {
        id: 'per_page',
        type: 'number',
        default: 10,
        label: __( 'Posts per page', 'enokh-blocks' ),
        description: __( 'Number of post to show per page.', 'enokh-blocks' ),
        group: __( 'Pagination', 'enokh-blocks' ),
        isSticky: true,
    },
    {
        id: 'page',
        type: 'number',
        default: 1,
        label: __( 'Page', 'enokh-blocks' ),
        description: __( 'Display posts from page.', 'enokh-blocks' ),
        group: __( 'Pagination', 'enokh-blocks' ),
    },
    {
        id: 'offset',
        type: 'number',
        default: undefined,
        label: __( 'Offset', 'enokh-blocks' ),
        description: __( 'Offset the result set by a specific number of items.', 'enokh-blocks' ),
        group: __( 'Pagination', 'enokh-blocks' ),
    },
    {
        id: 'search',
        type: 'text',
        default: '',
        label: __( 'Search', 'enokh-blocks' ),
        description: __( 'Show posts based on a keyword search.', 'enokh-blocks' ),
        group: __( 'Search', 'enokh-blocks' ),
    },
    {
        id: 'order',
        type: 'select',
        default: 'desc',
        selectOptions: [
            { value: 'desc', label: 'DESC' },
            { value: 'asc', label: 'ASC' },
        ],
        label: __( 'Order', 'enokh-blocks' ),
        description: __( 'Designates the ascending or descending order of the ‘orderby‘ parameter.', 'enokh-blocks' ),
        group: __( 'Order & Order by', 'enokh-blocks' ),
    },
    {
        id: 'orderby',
        type: 'select',
        default: 'date',
        selectOptions: [
            { value: 'id', label: 'Id' },
            { value: 'title', label: 'Title' },
            { value: 'slug', label: 'Slug' },
            { value: 'author', label: 'Author' },
            { value: 'date', label: 'Date' },
            { value: 'modified', label: 'Last modified date' },
            { value: 'parent', label: 'Parent id' },
            { value: 'menu_order', label: 'Menu order' },
        ],
        label: __( 'Order by', 'enokh-blocks' ),
        description: __( 'Sort retrieved posts by parameter.', 'enokh-blocks' ),
        group: __( 'Order & Order by', 'enokh-blocks' ),
    },
    {
        id: 'author',
        type: 'authorsSelect',
        default: [],
        dependencies: {
            filterName: 'enokh-blocks.editor.query-loop.author',
        },
        label: __( 'Authors', 'enokh-blocks' ),
        description: __( 'Show posts from authors. Search by name or ID.', 'enokh-blocks' ),
        group: __( 'Author', 'enokh-blocks' ),
    },
    {
        id: 'author_exclude',
        type: 'authorsSelect',
        default: [],
        dependencies: {
            filterName: 'enokh-blocks.editor.query-loop.author-exclude',
        },
        label: __( 'Exclude authors', 'enokh-blocks' ),
        description: __( 'Exclude posts from authors. Search by name or ID.', 'enokh-blocks' ),
        group: __( 'Author', 'enokh-blocks' ),
    },
    {
        id: 'tax_query',
        type: 'taxonomySelect',
        default: [],
        label: __( 'Taxonomies', 'enokh-blocks' ),
        description: __( 'Show posts from taxonomies. Search by name or ID.', 'enokh-blocks' ),
        group: __( 'Taxonomy', 'enokh-blocks' ),
        isRepeatable: true,
        repeatableDefaultValue: { taxonomy: '', terms: [], rest: '', includeChildren: true },
    },
    {
        id: 'tax_query_exclude',
        type: 'taxonomySelect',
        default: [],
        label: __( 'Exclude taxonomies', 'enokh-blocks' ),
        description: __( 'Exclude posts from taxonomies. Search by name or ID.', 'enokh-blocks' ),
        group: __( 'Taxonomy', 'enokh-blocks' ),
        isRepeatable: true,
        repeatableDefaultValue: { taxonomy: '', terms: [], rest: '', includeChildren: true },
    },
    {
        id: 'status',
        type: 'multiSelect',
        default: [],
        selectOptions: [
            { value: 'publish', label: __( 'Publish', 'enokh-blocks' ) },
            { value: 'pending', label: __( 'Pending', 'enokh-blocks' ) },
            { value: 'draft', label: __( 'Draft', 'enokh-blocks' ) },
            { value: 'auto-draft', label: __( 'Auto draft', 'enokh-blocks' ) },
            { value: 'future', label: __( 'Future', 'enokh-blocks' ) },
            { value: 'private', label: __( 'Private', 'enokh-blocks' ) },
            { value: 'inherit', label: __( 'Inherit', 'enokh-blocks' ) },
            { value: 'trash', label: __( 'Trash', 'enokh-blocks' ) },
            { value: 'any', label: __( 'Any', 'enokh-blocks' ) },
        ],
        label: __( 'Post status', 'enokh-blocks' ),
        description: __( 'Show posts by post status.', 'enokh-blocks' ),
        group: __( 'Status', 'enokh-blocks' ),
    },
    {
        id: 'parent',
        type: 'postsSelect',
        default: [],
        dependencies: {
            postType: 'post_type',
            filterName: 'enokh-blocks.editor.query-loop.include-parent',
        },
        label: __( 'Parent', 'enokh-blocks' ),
        description: __( 'Show posts from parents. Search by name or ID.', 'enokh-blocks' ),
        group: __( 'Post', 'enokh-blocks' ),
    },
    {
        id: 'parent_exclude',
        type: 'postsSelect',
        default: [],
        dependencies: {
            postType: 'post_type',
            filterName: 'enokh-blocks.editor.query-loop.exclude-parent',
        },
        label: __( 'Parent exclude', 'enokh-blocks' ),
        description: __( 'Do not show posts from parents. Search by name or ID.', 'enokh-blocks' ),
        group: __( 'Post', 'enokh-blocks' ),
    },
    {
        id: 'include',
        type: 'postsSelect',
        default: [],
        dependencies: {
            postType: 'post_type',
        },
        label: __( 'Include posts', 'enokh-blocks' ),
        description: __( 'Limit result set to specific posts. Search by name or ID.', 'enokh-blocks' ),
        group: __( 'Post', 'enokh-blocks' ),
    },
    {
        id: 'exclude',
        type: 'postsSelect',
        default: [],
        dependencies: {
            postType: 'post_type',
            filterName: 'enokh-blocks.editor.query-loop.exclude-posts-select',
        },
        label: __( 'Exclude posts', 'enokh-blocks' ),
        description: __( 'Ensure result set excludes specific posts. Search by name or ID.', 'enokh-blocks' ),
        group: __( 'Post', 'enokh-blocks' ),
    },
    {
        id: 'stickyPosts',
        type: 'select',
        default: 'include',
        selectOptions: [
            { value: 'include', label: 'Include' },
            { value: 'exclude', label: 'Exclude' },
            { value: 'ignore', label: 'Ignore' },
            { value: 'only', label: 'Only' },
        ],
        label: __( 'Sticky posts', 'enokh-blocks' ),
        description: __( 'Configure how sticky posts should show in the query.', 'enokh-blocks' ),
        group: __( 'Post', 'enokh-blocks' ),
    },
    {
        id: 'after',
        type: 'dateTimePicker',
        default: '',
        label: __( 'After', 'enokh-blocks' ),
        description: __( 'Limit response to posts published after a given date.', 'enokh-blocks' ),
        group: __( 'Date', 'enokh-blocks' ),
    },
    {
        id: 'before',
        type: 'dateTimePicker',
        default: '',
        label: __( 'Before', 'enokh-blocks' ),
        description: __( 'Limit response to posts published before a given date.', 'enokh-blocks' ),
        group: __( 'Date', 'enokh-blocks' ),
    },
];
