<?php

declare(strict_types=1);

namespace Enokh\UniversalTheme\Blocks\TabPanel;

use Enokh\UniversalTheme\Utility\BlockUtility;

use function Inpsyde\PresentationElements\renderTag;

class Renderer
{
    private Style $style;
    private BlockUtility $blockUtility;

    public function __construct(Style $style, BlockUtility $blockUtility)
    {
        $this->style = $style;
        $this->blockUtility = $blockUtility;
    }

    public function render(array $attributes, string $content, \WP_Block $block): string
    {

        if (empty($attributes['uniqueId'])) {
            return $this->v1Renderer($attributes, $content);
        }

        $css = $this->style->withSettings($attributes)
            ->generate()
            ->output();

        add_filter(
            $this->blockUtility->cssHookName(),
            static function (array $inlineCss) use ($css, $attributes): array {
                    $inlineCss[$attributes['uniqueId']] = $css;

                    return $inlineCss;
            }
        );

        $classNames = [
            'enokh-blocks-tabs',
            'enokh-blocks-tabs-' . ($attributes['uniqueId'] ?? ''),
        ];

        return renderTag(
            'div',
            get_block_wrapper_attributes([
                'class' => implode(' ', $classNames),
                'id' => 'enokh-blocks-tabs-' . ($attributes['uniqueId'] ?? ''),
                'data-mah-tabs' => '',
            ]),
            renderTag(
                'div',
                get_block_wrapper_attributes([
                    'class' => 'enokh-blocks-tabs-group',
                ]),
                $content
            )
        );
    }

    public function v1Renderer(array $attributes, string $content): string
    {
        $classes = ['enokh-blocks-tabs'];
        $tabClasses = ['tabs', 'needs-tab-control'];

        if ($attributes['disableTitle'] === true) {
            $tabClasses[] = 'is-disable-title';
        }

        ob_start();
        ?>

        <div class="<?= esc_attr(implode(' ', $classes)); ?>">

            <div class="<?= esc_attr(implode(' ', $tabClasses)); ?>" data-panelid="%%index%%">
                <div class="tab-control">
                    <!-- This will be a unordered list generated by FE JS -->
                </div>

                <div class="tab-group">
                    <?php echo $content // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped, Syde.Files.LineLength.TooLong?>
                </div><!-- /.tab-group -->
            </div>

        </div>
        <?php
        return ob_get_clean();
    }
}
