<?php

declare(strict_types=1);

namespace Enokh\UniversalTheme\Asset;

use Enokh\UniversalTheme\Style\InlineCssGenerator;
use Inpsyde\Assets\AssetManager;
use Inpsyde\Assets\Script;
use Inpsyde\Assets\Style;
use Inpsyde\Modularity;
use Psr\Container\ContainerInterface;

/**
 * @codeCoverageIgnore
 * phpcs:disable Inpsyde.CodeQuality.FunctionLength.TooLong
 */
class Module implements
    Modularity\Module\ServiceModule,
    Modularity\Module\ExecutableModule
{
    use Modularity\Module\ModuleClassNameIdTrait;

    public const PRESENTATION_HANDLE = 'enokh_blocks';

    public function services(): array
    {
        return [
            'blockInlineStyle' => static function (): Style {
                return (new Style(self::PRESENTATION_HANDLE . '-inline', ''))
                    ->withInlineStyles(
                        implode(
                            '',
                            apply_filters(InlineCssGenerator::INLINE_FILTER_HOOK, [])
                        )
                    );
            },
            BlockEditorScript::class => static function (ContainerInterface $container): Script {
                return (new BlockEditorScript(
                    $container->get(Modularity\Package::PROPERTIES)
                ))->createScript($container);
            },
            TermIconScript::class => static function (ContainerInterface $container): Script {
                return (new TermIconScript(
                    $container->get(Modularity\Package::PROPERTIES)
                ))->createScript($container);
            },
            TermIconStyle::class => static function (ContainerInterface $container): Style {
                return (new TermIconStyle(
                    $container->get(Modularity\Package::PROPERTIES)
                ))->createScript($container);
            },
            BlockEditorStyle::class => static function (ContainerInterface $container): Style {
                return (new BlockEditorStyle(
                    $container->get(Modularity\Package::PROPERTIES)
                ))->createStyle();
            },
            FrontOfficeScript::class => static function (ContainerInterface $container): Script {
                return (new FrontOfficeScript(
                    $container->get(Modularity\Package::PROPERTIES)
                ))->createScript($container);
            },
            FrontOfficeStyle::class => static function (ContainerInterface $container): Style {
                return (new FrontOfficeStyle(
                    $container->get(Modularity\Package::PROPERTIES)
                ))->createStyle();
            },
            CoreStyle::class => static function (ContainerInterface $container): Style {
                return (new CoreStyle(
                    $container->get(Modularity\Package::PROPERTIES)
                ))->createStyle();
            },
            CoreEditorStyle::class => static function (ContainerInterface $container): Style {
                return (new CoreEditorStyle(
                    $container->get(Modularity\Package::PROPERTIES)
                ))->createStyle();
            },
            ElementsStyle::class => static function (ContainerInterface $container): Style {
                return (new ElementsStyle(
                    $container->get(Modularity\Package::PROPERTIES)
                ))->createStyle();
            },
            ElementsEditorStyle::class => static function (ContainerInterface $container): Style {
                return (new ElementsEditorStyle(
                    $container->get(Modularity\Package::PROPERTIES)
                ))->createStyle();
            },
        ];
    }

    public function run(ContainerInterface $container): bool
    {

        add_action(
            AssetManager::ACTION_SETUP,
            static function (AssetManager $assetManager) use ($container): void {
                $assetManager->register(
                    $container->get(BlockEditorScript::class),
                    $container->get(BlockEditorStyle::class),
                    $container->get(FrontOfficeScript::class),
                    $container->get(FrontOfficeStyle::class),
                    $container->get(CoreStyle::class),
                    $container->get(CoreEditorStyle::class),
                    $container->get(ElementsStyle::class),
                    $container->get(ElementsEditorStyle::class),
                    $container->get('blockInlineStyle'),
                    $container->get(TermIconScript::class),
                    $container->get(TermIconStyle::class)
                );
            }
        );
        /**
         * Hook into the wp_footer action to output inline CSS.
         *
         * This callback function outputs a <style> tag with a unique ID and inline CSS.
         * The inline CSS is generated by applying the '_css_inline' filter, allowing plugins
         * or themes to inject custom styles.
         * Ensures that this action is executed at the very end of the footer.
         *
         * @phpcs:disable WordPress.Security.EscapeOutput.OutputNotEscaped
         */
        add_action('wp_footer', static function () {
            printf(
                "<style id='%s'>%s</style>",
                self::PRESENTATION_HANDLE . '-inline',
                implode('', apply_filters(InlineCssGenerator::INLINE_LATE_FILTER_HOOK, []))
            );
        }, 999999);

        /** @phpcs:enable */

        return true;
    }
}
